FROM python:3.11.4

# Install environment dependencies
RUN apt-get update \
    && apt-get -y install netcat-traditional \
    && apt-get clean

# Set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# Install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# Add app
COPY . /usr/src/app

# Run server
CMD ["./entrypoint.sh"]

